"""Added auction table

Revision ID: 806d482c80f8
Revises: b498329b07ce
Create Date: 2019-01-01 19:19:22.733943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806d482c80f8'
down_revision = 'b498329b07ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auction_type', sa.Integer(), nullable=True),
    sa.Column('auction_duration_hours', sa.Float(), nullable=True),
    sa.Column('auction_creator_id', sa.Integer(), nullable=True),
    sa.Column('item', sa.Text(), nullable=True),
    sa.Column('item_description', sa.Text(), nullable=True),
    sa.Column('minimum_bid', sa.Float(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auction_creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auction')
    # ### end Alembic commands ###
